### PR TITLE
Treat message with condition as more specific than upgrade message

### PR DESCRIPTION
**Pull request by samueltardieu**

### CODE REVIEW

**Comment by samueltardieu** [comment]
I cannot test it right away, work in progress.

**Comment by samueltardieu** [comment]
@Lineflyer This PR is deployed on Heroku for testing (we don't have a sandbox for that unfortunately). Could you test that it does what it is supposed to do? Note that the `kind` is interpreted before checking that a new version exists, so an expression `kind == "release"` would cover both actual and older releases (you can discriminate using `versionName` or `versionCode` if needed).

The expected behaviour is:
1- a message without a condition should not be prioritized over an upgrade instruction ;
1- a message with a condition should be prioritiezd over an upgrade instruction provided the condition matches.

(1) Seems to be working right now, as I have a former nightly installed and I see the note that nightly are working again. I would like you to confirm (2) (an older release should prompt an upgrade to the latest release).

**Comment by samueltardieu** [comment]
(incidentally, I would suggest to add a version check on the current message, as well to include a link to the current nightly along with the message so that people can upgrade)

**Comment by Lineflyer** [comment]
Sounds very good. Thanks @samueltardieu 
The message for the nightlies was only to play around with the system and have a gimmick for our nightly users :)
Before this modification it was only displayed on the newest nightly anyway, but now the condition makes sense.

I will test it on next occassion, where we need the system and let you know, in case something is not OK.

**Pull request merged**
