### PR TITLE
Use https for all cgeo server links

### PR DESCRIPTION
**Pull request by Lineflyer**
download.cgeo.org is using SSL meanwhile.
Additionally I have the problem, that I cant use the download links on https://www.cgeo.org/status.html with Google Chrome. Simply nothing happens. I assume this might be caused by that.

### CODE REVIEW

**Comment by Lineflyer** [comment]
Addon:
Indeed that is the reason:
```
Mixed Content: The site at 'https://www.cgeo.org/' was loaded over a secure connection, but the file at 'https://download.cgeo.org/cgeo-RC.apk' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.
```

**Comment by samueltardieu** [comment]
Applied, thanks!

**Comment by Lineflyer** [comment]
Thanks, but won't you want to update the repo to this state as well?

**Comment by samueltardieu** [comment]
Yes of course, I was just testing on Heroku first, the repository has been updated here as well.

**Comment by samueltardieu** [comment]
It reads "Closed" instead of "Merged" because my comment was sent before I pushed the main branch with your branch included – I use manual merges because I need to push on Heroku as well.

**Comment by Lineflyer** [comment]
Interesting...I must have looked into the commit history at the very moment after you closed and before you pushed. Sorry to bother :)

**Pull request closed without merging**
